# Generated by Django 5.1.7 on 2025-03-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_question_x"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="x",
        ),
    ]
